var shortid = require('shortid');
var _ = require('lodash');
var fs = require('fs-extra');

module.exports = function(currentUser, github, repoName, directoryPath){
	var user = github.getUser();

	var repoObj = {
	  "name": repoName,
	  "description": "React Native mobile app generated by BreezeBlocks.io",
	  "homepage": currentUser.github.profileUrl,
	};
	
	return new Promise(function(resolve, reject){
		user.createRepo(repoObj, function(err, res) {
			if(err) {
				fs.remove(directoryPath, function(err){
					if(err) console.error("error deleting", err);
				});
				reject(err);
			}
			else {
				resolve(res);
			}
		});
	});
};

