module.exports = function(currentUser, github, repoName){
	var user = github.getUser();

	var repoObj = {
	  "name": repoName,
	  "description": "React Native mobile app generated by BreezeBlocks.io",
	  "homepage": currentUser.github.profileUrl,
	}
	
	return new Promise(function(resolve, reject){
		user.createRepo(repoObj, function(err, res) {
			if(err) reject(err);
			else {
				console.log("repo created");
				resolve(res);
			}
		});
	})
}

