module.exports = function(currentUser, github, repoName){
	var user = github.getUser();

	var repoObj = {
	  "name": repoName,
	  "description": "React Native mobile app generated by BreezeBlocks.io",
	  "homepage": currentUser.github.profileUrl,
	}
	
/*	new Promise(function(resolve, reject){
		return user.repos(function(err, repos){
			if(err) reject(err);
			else {
				var keys = Object.keys(repos);
				keys.forEach(function(index){
					if(repos[index].name === repoName){
						console.log("Checking name")
						return repoObj.name = repoName + '_1';
					} 
				})
				resolve(repos);
			}
		})
	})
	.then(function(){*/
		return new Promise(function(resolve, reject){
			user.createRepo(repoObj, function(err, res) {
				if(err) reject(err);
				else {
					console.log("repo created");
					resolve(res);
				}
			});
		})
	//})
}

